controllers/login.py
from flask import *
import MySQLdb
import MySQLdb.cursors
import extensions
import config
import hash

login = Blueprint('login', __name__, template_folder='templates')

db = extensions.connect_to_database()

@login.route('/login', methods = ['GET', 'POST'])
def login_route():
    options = {
        "isUsernameEmpty": False,
        "isPasswordEmpty": False,
        "isUsernameWrong": False,
        "isPassowrdWrong": False
    }
    if request.method == 'POST':
        '''if not 'username' in request.args or not 'password' in request.args:
            if not 'username' in request.args:
                options['isUsernameEmpty'] = True
            if not 'password' in request.args:
                options['isPasswordEmpty'] = True
            return render_template("login.html", **options)'''
        
        username = request.form['username']
        passwordLogin = request.form['password']

    

        #print "username = ", username
        #print "passwordLogin = ", passwordLogin


        #print "username = ", username
        #print "passwordLogin = ", passwordLogin
        
        if username == '' or passwordLogin == '':
            if username == '':
                options['isUsernameEmpty'] = True
            if passwordLogin == '':
                options['isPasswordEmpty'] = True
            return render_template("login.html", **options)
        
        cur1 = db.cursor()
        cur1.execute('SELECT username FROM UserInfo')
        results1 = cur1.fetchall()
        same = 0
        for user in results1:
            if user['username'] == username:
                same += 1
        if same == 0:
            options['isUsernameWrong'] = True
        if options['isUsernameWrong']:
            return render_template("login.html", **options)
        
        
        cur2 = db.cursor()
        cur2.execute('SELECT password FROM UserInfo WHERE username = %s', (username, ))
        results2 = cur2.fetchall()
        for password in results2:
            #print 'passwordType=', type(password) 
            salt = hash.getSalt(password['password'])
            hashPassword = hash.hashPasswordWithSalt(passwordLogin, salt)

            
            #print "hashPassword = ", hashPassword
            #print "password['password'] = ", password['password']

            if password['password'] != hashPassword:
                options['isPassowrdWrong'] = True
        if options['isPassowrdWrong']:
            return render_template("login.html", **options)

        #print "password check right"

        #both username and password is correct
        if 'username' in session:
            session.pop('username', None)
        
        session['username'] = username
        return redirect(url_for('main.main_route'))
        
    return render_template("login.html")

  

controllers/logout.py
from flask import Flask, redirect, url_for, Blueprint
from flask import *
import MySQLdb
import MySQLdb.cursors
import extensions
import config
import hash

logout = Blueprint('logout', __name__, template_folder='templates')

@logout.route('/logout')
def logout_route():
        session.pop('username', None)
        return redirect(url_for('main.main_route'))

controllers/restaurants.py
# from sklearn.feature_extraction.text import TfidfVectorizer
# from numpy import array, dot
from flask import *
import extensions 
from flask import url_for
import json
import MySQLdb
import MySQLdb.cursors

restaurants = Blueprint('restaurants', __name__, template_folder='templates')

db = extensions.connect_to_database()

@restaurants.route('/restaurants', methods = ['GET', 'POST'])
def restaurants_route():
	if 'name' not in request.args:
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			lines = []
			for item in json_decode:
				lines.append(item)

			lines = sorted(lines, key=lambda k: k['stars'], reverse=True)

			i = 0
			name = []
			address = []
			postal_code = []
			stars = []
			review_count = []
			general = True
			city = []
			state = []
			for item in lines:
				name.append(item.get('name'))
				address.append(item.get('address'))
				postal_code.append(item.get('postal_code'))
				stars.append(item.get('stars'))
				review_count.append(item.get('review_count'))
				city.append(item.get('city'))
				state.append(item.get('state'))
				i += 1
				if i == 200:
					break
			print('items in file:')
			print(i)

			username = ''
			if "username" in session:
				username = session['username']

			options = {
				"general": general,
				"name": name,
				"address": address,
				"zipcode": postal_code,
				"rating": stars,
				"reviewcount": review_count,
				"city": city,
				"state": state,
				"username": username
			}
			return render_template("restaurants.html", **options)
	else:
		name = request.args.get('name')

		username = ''
		favourite = False
		if "username" in session:
			username = session['username']
			cur1 = db.cursor()
			cur1.execute('SELECT restaurant FROM Favorite WHERE username = %s', (username, ))
			results = cur1.fetchall()

			for res in results:
				if res['restaurant'] == name:
					favourite = True
			print(username)

		if request.method == 'POST':
			if 'username' not in session:
				return redirect(url_for('login.login_route'))

			if favourite == False:
				cur2 = db.cursor()
				cur2.execute("INSERT INTO Favorite (username, restaurant) VALUES (%s, %s)",(username, name))
				favourite = True 
			elif favourite == True:
				cur3 = db.cursor()
				cur3.execute("DELETE FROM Favorite WHERE restaurant=%s", (name, ))
				favourite = False
    		
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			businessid = ''
			neighborhood = ''
			address = ''
			city = ''
			state = ''
			zipcode = ''
			latitude = ''
			longitude = ''
			rating = ''
			reviewcount = ''
			isopen = ''
			attributes = ''
			categories = ''
			hours = ''
			general = False
			for item in json_decode:
				if item.get('name') == name:
					businessid = item.get('business_id')
					neighborhood = item.get('neighborhood')
					address = item.get('address')
					city = item.get('city')
					state = item.get('state')
					zipcode = item.get('postal_code')
					latitude = item.get('latitude')
					longitude = item.get('longitude')
					rating = item.get('stars')
					reviewcount = item.get('review_count')
					isopen = item.get('is_open')
					attributes = item.get('attributes')
					categories = item.get('categories')
					hours = item.get('hours')

			options = {
				"general": general,
				"name": name,
				"businessid": businessid,
				"neighborhood": neighborhood,
				"address": address,
				"city": city,
				"state": state,
				"zipcode": zipcode,
				"latitude": latitude,
				"longitude": longitude,
				"rating": rating,
				"reviewcount": reviewcount,
				"isopen": isopen,
				"attributes": attributes,
				"categories": categories,
				"hours": hours,
				"favourite": favourite,
				"username": username
			}
		
			return render_template("restaurants.html", **options)

controllers/search.py
from flask import *
from sklearn.feature_extraction.text import TfidfVectorizer
from extensions import connect_to_database
import json
import sklearn.metrics.pairwise as smp

name_list = []
address_list = []
with open('business_LV.json', 'r') as inputFile:
	json_decode = json.load(inputFile)
	for item in json_decode:
		name_list.append(item.get('name'))
		address_list.append(item.get('address'))

name_vectorizer = TfidfVectorizer(min_df=1)
name_mat = name_vectorizer.fit_transform(name_list).toarray()
address_vectorizer = TfidfVectorizer(min_df=1)
address_mat = address_vectorizer.fit_transform(address_list).toarray()

search = Blueprint('search', __name__, template_folder = 'templates')

# name_mat = extensions.get_name_mat()
# address_mat = extensions.get_address_mat()

@search.route('/search', methods = ['GET', 'POST'])
def search_route():
	username = ''
	if 'username' in session:
		username = session['username']
	select = request.form.get('sort')
	if select == "name":
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			score = smp.cosine_similarity(name_mat, name_vectorizer.transform([request.form.get('data')]))
			index = sorted(range(len(score)), key = lambda k:score[k], reverse = True)
			if score[index[0]] == 0:
				outofrange = True
				options = {
					"outofrange": outofrange,
					"select": select,
					"value": request.form.get('data'),
					"username": username
				}
				return render_template("search.html", **options)
			outofrange = False
			i = 0
			name = []
			address = []
			postal_code = []
			stars = []
			review_count = []
			city = []
			state = []
			for idx in index:
				if score[idx] == 0:
					break
				else:
					name.append(json_decode[idx].get('name'))
					address.append(json_decode[idx].get('address'))
					postal_code.append(json_decode[idx].get('postal_code'))
					stars.append(json_decode[idx].get('stars'))
					review_count.append(json_decode[idx].get('review_count'))
					city.append(json_decode[idx].get('city'))
					state.append(json_decode[idx].get('state'))
					i += 1
					if i == 200:
						break
			options = {
				"outofrange": outofrange,
				"name": name,
				"address": address,
				"zipcode": postal_code,
				"rating": stars,
				"reviewcount": review_count,
				"city": city,
				"state": state,
				"username": username
			}
			return render_template("search.html", **options)
	elif select == "address":
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			score = smp.cosine_similarity(address_mat, address_vectorizer.transform([request.form.get('data')]))
			index = sorted(range(len(score)), key = lambda k:score[k], reverse = True)
			if score[index[0]] == 0:
				outofrange = True
				options = {
					"outofrange": outofrange,
					"select": select,
					"value": request.form.get('data'),
					"username": username
				}
				return render_template("search.html", **options)
			outofrange = False
			i = 0
			name = []
			address = []
			postal_code = []
			stars = []
			review_count = []
			city = []
			state = []
			for idx in index:
				if score[idx] == 0:
					break
				else:
					name.append(json_decode[idx].get('name'))
					address.append(json_decode[idx].get('address'))
					postal_code.append(json_decode[idx].get('postal_code'))
					stars.append(json_decode[idx].get('stars'))
					review_count.append(json_decode[idx].get('review_count'))
					city.append(json_decode[idx].get('city'))
					state.append(json_decode[idx].get('state'))
					i += 1
					if i == 200:
						break
			options = {
				"outofrange": outofrange,
				"name": name,
				"address": address,
				"zipcode": postal_code,
				"rating": stars,
				"reviewcount": review_count,
				"city": city,
				"state": state,
				"username": username
			}
			return render_template("search.html", **options)

	elif select == "zipcode":
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			list = []
			for item in json_decode:
				if request.form.get('data') == item.get('postal_code'):
					list.append(item)
			list = sorted(list, key=lambda k: k['stars'], reverse=True)
			
			if len(list) == 0:
				outofrange = True
				options = {
					"outofrange": outofrange,
					"select": select,
					"value": request.form.get('data'),
					"username": username
				}
				return render_template("search.html", **options)
			else:
				i = 0
				name = []
				address = []
				postal_code = []
				stars = []
				review_count = []
				outofrange = False
				city = []
				state = []
				for item in list:
					name.append(item.get('name'))
					address.append(item.get('address'))
					postal_code.append(item.get('postal_code'))
					stars.append(item.get('stars'))
					review_count.append(item.get('review_count'))
					city.append(item.get('city'))
					state.append(item.get('state'))
					i += 1
					if i == min(200, len(list)):
						break
				options = {
					"outofrange": outofrange,
					"name": name,
					"address": address,
					"zipcode": postal_code,
					"rating": stars,
					"reviewcount": review_count,
					"city": city,
					"state": state,
					"username": username
				}
				return render_template("search.html", **options)

	elif select == "rating":
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			list = []
			for item in json_decode:
				if float(request.form.get('data')) == float(item.get('stars')):
					list.append(item)
			list = sorted(list, key=lambda k: k['review_count'], reverse=True)
			
			if len(list) == 0:
				outofrange = True
				options = {
					"outofrange": outofrange,
					"select": select,
					"value": request.form.get('data'),
					"username": username
				}
				return render_template("search.html", **options)
			else:
				i = 0
				name = []
				address = []
				postal_code = []
				stars = []
				review_count = []
				outofrange = False
				city = []
				state = []
				for item in list:
					name.append(item.get('name'))
					address.append(item.get('address'))
					postal_code.append(item.get('postal_code'))
					stars.append(item.get('stars'))
					review_count.append(item.get('review_count'))
					city.append(item.get('city'))
					state.append(item.get('state'))
					i += 1
					if i == min(200, len(list)):
						break
				options = {
					"outofrange": outofrange,
					"name": name,
					"address": address,
					"zipcode": postal_code,
					"rating": stars,
					"reviewcount": review_count,
					"city": city,
					"state": state,
					"username": username
				}
				return render_template("search.html", **options)

	elif select == "reviewcount":
		with open('/vagrant/EECS549/business_LV.json', 'r') as inputFile:
			json_decode = json.load(inputFile)
			list = []
			for item in json_decode:
				if abs(int(request.form.get('data')) - int(item.get('review_count'))) < 15:
					list.append(item)
			list = sorted(list, key=lambda k: k['stars'], reverse=True)
			
			if len(list) == 0:
				outofrange = True
				options = {
					"outofrange": outofrange,
					"select": select,
					"value": request.form.get('data'),
					"username": username
				}
				return render_template("search.html", **options)
			else:
				i = 0
				name = []
				address = []
				postal_code = []
				stars = []
				review_count = []
				outofrange = False
				city = []
				state = []
				for item in list:
					name.append(item.get('name'))
					address.append(item.get('address'))
					postal_code.append(item.get('postal_code'))
					stars.append(item.get('stars'))
					review_count.append(item.get('review_count'))
					city.append(item.get('city'))
					state.append(item.get('state'))
					i += 1
					if i == min(200, len(list)):
						break
				options = {
					"outofrange": outofrange,
					"name": name,
					"address": address,
					"zipcode": postal_code,
					"rating": stars,
					"reviewcount": review_count,
					"city": city,
					"state": state,
					"username": username
				}
				return render_template("search.html", **options)

controllers/signup.py
from flask import Flask, session, redirect, url_for, escape, request, Blueprint, render_template
import MySQLdb
import MySQLdb.cursors
from extensions import *
import config
import hash

signup = Blueprint('signup', __name__, template_folder='templates')

db = connect_to_database()

@signup.route('/signup', methods = ['GET', 'POST'])
def signup_route():
    if 'username' in session:
        return redirect(url_for('user.user_route'))
    
    if request.method == 'POST':
        username = request.form.get('username')
        firstname = request.form.get('firstname')
        lastname = request.form.get('lastname')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        email = request.form.get('email')
        
        isUsernameRepeated = False
        isPassword1TooShort = False
        isPassword12Mismatch = False
        
        cur1 = db.cursor()
        cur1.execute('SELECT username FROM UserInfo')
        result1 = cur1.fetchall()
        for user in result1:
            if user['username'] == username:
                isUsernameRepeated = True
                
        if not password1 == password2:
            isPassword12Mismatch = True

        if isStrLengthLessThanN(password1, 7):
            isPassword1TooShort = True
        
        options = {
            "edit" :False,
            "method" :'POST',
            "isUsernameRepeated": isUsernameRepeated,
            "isPassword1TooShort": isPassword1TooShort,
            "isPassword12Mismatch": isPassword12Mismatch
        }
        for key in options:
            if options[key] == True:
                return render_template("signup.html", **options)
        
        hashPassword = hash.hashPassword(password1)
        
        cur2 = db.cursor()
        add_user = ("INSERT INTO UserInfo (username, firstname, lastname, password, email) VALUES (%s, %s, %s, %s, %s)")
        data_user = (username, firstname, lastname, hashPassword, email)
        cur2.execute(add_user, data_user)
        return redirect(url_for('login.login_route'))
    
    options = {
        "edit" : False,
        "method" : 'GET'     
    }
    return render_template("signup.html", **options)    

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<meta charset="utf-8">
<meta name="description" content="las vegas restaurants">
<meta name="author" content="Yuan, haibo">
<head>
    <title>Las Vegas Restaurants</title>
</head>
<body style="background-color: #E5E2DB;">
	<style>
        .header{ color :orange; text-align: center; font-size: 40px; }

        .fit { max-width: 100%; max-height: 100%; }

        p, form{ display: inline; }

        .para{ background-color:grey; color: orange; font-size: 18px; }

        .options{ background-color: dimgrey; color: orange;
            font-size: 16px; font-family: Times New Roman; }

        .button { background-color: dimgrey; border: none; color: orange;
            padding: 5px 5px; text-align: center; text-decoration: none;
            display: inline-block; margin: 4px 2px; font-family: Times New Roman; }
        
        input[type=text]{ background-color: dimgrey; color: orange; border: none;
            font-family: Times New Roman; font-size: 18px; }

        ul.cols { background-color:grey; color: orange; font-size: 18px; list-style-type: none; columns: 4; }

        ul.navbar { list-style-type: none; margin: 0; padding: 0; overflow: hidden; background-color: orange; }

        li.navbar { float: left; }

        li.navbar a { display: block; color: dimgrey; text-align: center; padding: 14px 16px; text-decoration: none; }

        li.navbar a:hover { background-color: darkorange; color: black; }

        li.navbar2 { float: right; }

        li.navbar2 a { display: block; color: dimgrey; text-align: center; padding: 14px 16px; text-decoration: none; }

        li.navbar2 a:hover { background-color: darkorange; color: black; }

        p + ul { margin-top: 0px; }

        table{ border-collapse:collapse; border:1px solid; }

        table td{ border:1px solid; }

        table th{ border:1px solid; }

        footer {
            font-size: 20px;
            position: absolute;
            bottom: 0px;
            right: 50px;
            height: 35px;
            margin: 0px 0px 0px 0px;
            text-align: right;
            padding: 10px 30px;
            color :orange;
        }

    </style>
  <ul class="navbar">
        <li class="navbar"><a href="{{url_for('main.main_route')}}"><b>Home</b></a></li>
        <li class="navbar"><a href="{{url_for('restaurants.restaurants_route')}}"><b>Restaurants</b></a></li>
        <li class="navbar2"><a href="{{url_for('login.login_route')}}"><b>Log In</b></a></li>
        <li class="navbar2"><a href="{{url_for('signup.signup_route')}}"><b>Signup</b></a></li>
        {% if 'username' in session %}
            <li class="navbar2"><a href="{{url_for('user.user_route')}}"><b>{{username}}</b></a></li>
            <li class="navbar2"><a href="{{url_for('logout.logout_route')}}"><b>Log Out</b></a></li>
        {% endif %}
   </ul>


    <h1 class="header">Las Vegas Restaurants</h1>

    <!--<footer> Yuan Tian, Haibo Shen</footer>-->
    {% block content %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<style>
.search {
	position: relative;
	top: 100px;
	width: 100%;
}
select { 
	width: 200px; 
	height: 70px;
}

input[type=text] {
	position: relative;
	width: 600px; 
	height: 70px;
}

input[type=submit] {
	position: relative;
	width: 100px; 
	height: 40px;
}

.img{
	position: relative;
	width: 1200px;
	height: 400px;
}
</style>

<center><img src="/static/lasvegas.jpg" alt="Las Vegas" class=img></center>

<center class="search">
<form method="post", action="{{url_for('search.search_route')}}">
    <select name="sort" class="options">
            <option value="">Find</option>
            <option value="name">Name</option>
            <option value="address">Address</option>
            <option value="zipcode">Zipcode</option>
            <option value="rating">Rating</option>
            <option value="reviewcount">Review Count</option>
    </select>
    <input type="text" name="data" class="para" />
    <input class="button" type="submit" value="Search" />
</form>
</center>
{% endblock %}

templates/restaurants.html
{% extends "base.html" %}
{% block content %}
<style>
  .ratings {
    position: relative;
    vertical-align: middle;
    display: inline-block;
    color: #b1b1b1;
    overflow: hidden;
  }

  .full-stars{
    position: absolute;
    left: 0;
    top: 0;
    white-space: nowrap;
    overflow: hidden;
    color: #fde16d;
  }

  .empty-stars:before,
  .full-stars:before {
    content: "\2605\2605\2605\2605\2605";
    font-size: 14pt;
  }

  .empty-stars:before {
    -webkit-text-stroke: 1px #848484;
  }

  .full-stars:before {
    -webkit-text-stroke: 1px orange;
  }
</style>

{% if general %}
  <div>
  	{% for i in range(name|length) %}
  		<hr>
  		<p>{{ i+1 }}. </p>
  		<a href="{{url_for('restaurants.restaurants_route', name=name[i]) }}"> {{name[i]}} </a> <br>
      <div class="ratings">
        <div class="empty-stars"></div>
        <div class="full-stars" style="width:calc(({{rating[i]}}|int())/5*100%)"></div>
      </div>
  		<p> &nbsp {{reviewcount[i]}} reviews </p><br>
      {% if address[i] %}
        <p> {{address[i]}} </p><br>
      {% endif %}
      <p> {{city[i]}} {{state[i]}}, {{zipcode[i]}} </p><br>
  	{% endfor %}
  </div>

  <div class="pagination">
    <a href="restaurants">&laquo;</a>
    <a href="restaurants" class="active">1</a>
    <a href="restaurants">2</a>
    <a href="restaurants">3</a>
    <a href="restaurants">4</a>
    <a href="restaurants">5</a>
    <a href="restaurants">6</a>
    <a href="restaurants">7</a>
    <a href="restaurants">8</a>
    <a href="restaurants">9</a>
    <a href="restaurants">10</a>
    <a href="restaurants">11</a>
    <a href="restaurants">12</a>
    <a href="restaurants">13</a>
    <a href="restaurants">14</a>
    <a href="restaurants">15</a>
    <a href="restaurants">16</a>
    <a href="restaurants">17</a>
    <a href="restaurants">18</a>
    <a href="restaurants">19</a>
    <a href="restaurants">20</a>
    <a href="restaurants">&raquo;</a>
  </div>
{% else %}
  <p><font size="5" face="verdana"> {{name}} </p><br>

  <div class="ratings">
    <div class="empty-stars"></div>
    <div class="full-stars" style="width:calc(({{rating}}|int())/5*100%)"></div>
  </div>
  <p><font size="3" face="verdana"> {{rating}} &nbsp {{reviewcount}} reviews </p><br>

  <br>

  {% for category in categories%}
    <p><font size="3" face="verdana"> {{category}} </font></p>
    {% if not loop.last %} 
      <p><font size="3" face="verdana"> , </font></p>
    {% endif %}
  {% endfor %}
  <br><br>

  {% if neighborhood %}
    <p><font size="3" face="verdana"> neighborhood: {{neighborhood}} </font></p><br>
  {% endif %}

  {% if address %}
    <p><font size="3" face="verdana"> {{address}} </font></p><br>
  {% endif %}

  {% if city %}
    <p><font size="3" face="verdana"> {{city}}, </font></p>
  {% endif %}
  {% if state %}
    <p><font size="3" face="verdana"> {{state}} </font></p>
  {% endif %}
  {% if zipcode %}
    <p><font size="3" face="verdana"> {{zipcode}} </font></p><br><br>
  {% endif %}
  
  {% if hours %}
    <p><font size="4" face="verdana" color="red"> Hours </font></p><br>
    {% for day in hours %}
      {% set list = day.split() %}
         {{list[0]}}, {{list[1]}} <br>
    {% endfor %}
  {% endif %}
  <br>

  {% if favourite %}
    <form method="post">
      <button type="submit">Unfavorite</button>
    </form>
  {% else %}
    <form method="post">
      <button type="submit">Favorite</button>
    </form>
  {% endif %}
{% endif %}
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block content %}
<style>
  .ratings {
  position: relative;
  vertical-align: middle;
  display: inline-block;
  color: #b1b1b1;
  overflow: hidden;
	}

	.full-stars{
	  position: absolute;
	  left: 0;
	  top: 0;
	  white-space: nowrap;
	  overflow: hidden;
	  color: #fde16d;
	}

	.empty-stars:before,
	.full-stars:before {
	  content: "\2605\2605\2605\2605\2605";
	  font-size: 14pt;
	}

	.empty-stars:before {
	  -webkit-text-stroke: 1px #848484;
	}

	.full-stars:before {
	  -webkit-text-stroke: 1px orange;
	}

	.search {
	position: relative;
	top: 100px;
	width: 100%;
	}

	select { 
		width: 200px; 
		height: 70px;
	}

	input[type=text] {
		position: relative;
		width: 600px; 
		height: 70px;
	}

	input[type=submit] {
		position: relative;
		width: 100px; 
		height: 40px;
	}

</style>

{% if outofrange %}
	<center class="search">
		<form method="post", action="{{url_for('search.search_route')}}">
		    <select name="sort" class="options">
		            <option value="">Find</option>
		            <option value="name">Name</option>
		            <option value="address">Address</option>
		            <option value="zipcode">Zipcode</option>
		            <option value="rating">Rating</option>
		            <option value="reviewcount">Review Count</option>
		    </select>
		    <input type="text" name="data" class="para" />
		    <input class="button" type="submit" value="Search" />
		</form>
	<br><br>
	<p><font size="3" face="verdana"> No Results for {{select}} {{value}}</font></p><br>
	</center>
	{% else %}
	{% for i in range(name|length) %}
  		<hr>
  		<p>{{ i+1 }}. </p>
  		<a href="{{url_for('restaurants.restaurants_route', name=name[i]) }}"> {{name[i]}} </a> <br>
      <div class="ratings">
        <div class="empty-stars"></div>
        <div class="full-stars" style="width:calc(({{rating[i]}}|int())/5*100%)"></div>
      </div>
  		<p> &nbsp {{reviewcount[i]}} reviews </p><br>
      {% if address[i] %}
        <p> {{address[i]}} </p><br>
      {% endif %}
      <p> {{city[i]}} {{state[i]}}, {{zipcode[i]}} </p><br>
  	{% endfor %}
{% endif %}

{% endblock %}